version: '3.8'

services:
  n8n-mcp:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    image: n8n-mcp:latest
    container_name: n8n-mcp-server
    restart: unless-stopped
    
    # Environment variables (override with your .env file)
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      # Mount your .env file or set these directly:
      # - N8N_BASE_URL=https://your-n8n-instance.com
      # - N8N_API_KEY=your-api-key-here
      # - REQUEST_TIMEOUT=30000
      # - MAX_RETRY_ATTEMPTS=3
    
    # Mount your .env file (recommended approach)
    volumes:
      - ./.env:/app/.env:ro
      # Optional: Mount logs directory
      - ./logs:/app/logs
    
    # For debugging - expose stdio (remove in production)
    stdin_open: true
    tty: true
    
    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('MCP Server is healthy')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Resource limits (adjust as needed)
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    
    # Network (if you need to connect to other containers)
    # networks:
    #   - n8n-network

# Optional: Define networks
# networks:
#   n8n-network:
#     driver: bridge

# Optional: Define volumes for persistence
volumes:
  logs:
    driver: local 